repositories {
    google()
    mavenCentral()
}

ext.postBuildExtras = {
    android {
        defaultConfig {
            minSdkVersion 24
        }
        sourceSets {
            main {
                java.srcDirs += 'src/main/java'
                kotlin.srcDirs += 'src/main/java'
            }
        }
    }
}

dependencies {
    implementation 'com.clerk:clerk-android-api:0.2.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
